# Generated by Django 4.1.7 on 2023-02-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'transacoes'},
        ),
    ]
